<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="AspNetCoreHero.Extensions.Caching" Version="1.1.0" />
    <PackageReference Include="audit-trail" Version="1.1.6" />
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.1" />
	  <PackageReference Include="Npgsql" Version="9.0.3" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CourtApp.Application\CourtApp.Application.csproj" />
    <ProjectReference Include="..\CourtApp.Domain\CourtApp.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Migrations\Identity\" />
    <Folder Include="Migrations\App\" />
  </ItemGroup>
</Project>
